Add verbosity, if expose key will rotate

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -63,10 +63,14 @@ jobs:
           SSH_WEB_PATH: ${{ secrets.SSH_WEB_PATH }}
           BRANCH_NAME: ${{ github.ref_name }}
         run: |
+          #!/usr/bin/env bash
+
+          set -ex -o pipefail
+
           # Save the private key for SSH
-          mkdir -p ~/.ssh
+          mkdir -pv ~/.ssh
           echo "${SSH_KEY}" > "~/.ssh/id_${SSH_USER}"
-          chmod 600 "~/.ssh/id_${SSH_USER}"
+          chmod -v 400 "~/.ssh/id_${SSH_USER}"
 
           # Copy the artifact to the Remote
           scp -i "~/.ssh/id_${SSH_USER}" -P "${SSH_PORT}" project.zip "${SSH_USER}@${SSH_HOST}:${SSH_WEB_PATH}/${BRANCH_NAME}"
@@ -78,3 +82,6 @@ jobs:
             unzip ./project.zip
             rm ./project.zip
           EOF
+
+          # Cleanup the secret
+          rm -rfv "~/.ssh/id_${SSH_USER}" "~/.ssh/id_${SSH_USER}.pub"
